SoundMixer/SoundMixer/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('categories.urls')),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
]

SoundMixer/categories/urls.py
from django.urls import path

from . import views

app_name = 'categories'
urlpatterns = [
    path('', views.taglist, name='tag_list'),
    path('tag/<str:tag_name>', views.gettagsongs, name="get_tag_songs"),
    path('song/<int:song_id>/', views.song, name="song"),
    path('song/<int:song_id>/<str:song_id_list>/', views.song, name="song"),
    path('submit/song', views.submitsong, name="submit_song"),
    path('submit/tag', views.submittag, name="submit_tag"),
    path('search/', views.search, name="search"),
    path('signup/', views.signup.as_view(), name='signup'),
]

SoundMixer/categories/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Song(models.Model):
    name = models.CharField(max_length=140)
    link = models.CharField(max_length=50)
    tags = models.ManyToManyField(Category)

    def __str__(self):
        return self.name

SoundMixer/categories/forms.py
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy

from django import forms
from .models import Category

def validate_tag(value):
    # determines if a fraction name is a real fraction
    # or a bunch of gibberish
    try:
        Category.objects.get(name= value.lower())
    except:
        raise ValidationError(
            gettext_lazy('%(value)s is not a valid tag'),
            params={'value': value},
        )

class TagField(forms.CharField):
    def to_python(self, value):
        # Normalizes the data to a list of strings.
        # Return an empty list if no input was given.
        if not value:
            return []
        value = value.lower()
        t_list = value.split(',')
        # eliminates any whitespace on the begining or end of a fraction name.
        t_list = [x.strip() for x in t_list]
        return t_list

    def validate(self, value):
        # Check if list contains only real fractions
        # Use the parent's handling of required fields, etc.
        super().validate(value)
        for tag in value:
            validate_tag(tag)

class LinkField(forms.CharField):
    def to_python(self, value):
        components = value.split('?v=')
        info = components[-1].split('&')
        return info[0]

class LowerCharField(forms.CharField):
    def to_python(self, value):
        return value.lower()

class SongForm(forms.Form):
    #used to make a new post in the text_post view
    name = forms.CharField(label = 'Post Title', max_length = 280)
    link = LinkField(label = 'Post link', max_length = 50)
    tags = TagField(label = 'List tags (seperated by a comma)', max_length = 1000)

class SearchForm(forms.Form):
    include = TagField(label = 'Must include:', max_length = 1000, required=False)
    exclude = TagField(label = 'Can\'t have', max_length = 1000, required=False)

class TagForm(forms.Form):
    tag = LowerCharField(label = 'Tag name', max_length = 30)

class AddTagForm(forms.Form):
    tags = TagField(label = 'Add more tags', max_length = 1000)

SoundMixer/categories/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from random import randint
from django.db.models import Count

from .forms import SongForm, SearchForm, TagForm, AddTagForm

from .models import Category, Song

def getrandomsongid(song_id_list):
    #this 'list' is a string so we have to process it a bit first
    song_id_list = song_id_list.replace("[", "")
    song_id_list = song_id_list.replace("]", "")
    real_list = song_id_list.split(',')
    rand_id = randint(0, len(real_list) - 1)
    return real_list[rand_id]

def taglist(request):
    tag_list = Category.objects.annotate(s_count=Count('song')).order_by('-s_count')
    context = {
        'tag_list': tag_list,
    }
    return render(request, 'categories/tags.html', context)

def songlist(request, songquerry):
    song_id_list = []
    for song in songquerry:
        song_id_list.append(song.id)
    context = {
        'song_list': songquerry,
    }
    if song_id_list:
        random_song_id = getrandomsongid(str(song_id_list))
        random_song = Song.objects.get(id = random_song_id)
        context['song_id_list'] = song_id_list
        context['random_song'] = random_song
    return render(request, 'categories/list.html', context)

def gettagsongs(request, tag_name):
    tag = Category.objects.get(name=tag_name)
    songquerry = Song.objects.filter(tags=tag)
    return songlist(request, songquerry)

def search(request):
    if (request.method == "POST"):
        form = SearchForm(request.POST)
        if form.is_valid():
            song_list = Song.objects.all()
            for tag_name in form.cleaned_data['include']:
                tag = Category.objects.get(name=tag_name)
                song_list = song_list & Song.objects.filter(tags=tag)
            for tag_name in form.cleaned_data['exclude']:
                tag = Category.objects.get(name=tag_name)
                song_list = song_list & Song.objects.exclude(tags=tag)
            return songlist(request, song_list)
    else:
        form = SearchForm()
    return render(request, 'categories/search.html', { 'form': form })


def song(request, song_id, song_id_list = ''):
    song = Song.objects.get(id=song_id)
    if song_id_list:
        random_song_id = getrandomsongid(song_id_list)
        random_song = Song.objects.get(id = random_song_id)
    if (request.method == "POST"):
        form = AddTagForm(request.POST)
        if form.is_valid():
            for tag in form.cleaned_data['tags']:
                song.tags.add(Category.objects.get(name= tag))
            song.save()
    else:
        form = AddTagForm()
    context = {
        'song': song,
        'form': form,
    }
    if song_id_list:
        context['song_id_list'] = song_id_list
        context['random_song'] = random_song
    return render(request, 'categories/song.html', context)

def submitsong(request):
    if (request.method == "POST"):
        form = SongForm(request.POST)
        if form.is_valid():
            new_song = Song(
                name = form.cleaned_data['name'],
                link = form.cleaned_data['link'],
                )
            new_song.save()
            for tag in form.cleaned_data['tags']:
                new_song.tags.add(Category.objects.get(name= tag))
            new_song.save()
            #currently returns to the main page.
            return HttpResponseRedirect('/')
    else:
        form = SongForm()
    return render(request, 'categories/submit_song.html', { 'form': form })

def submittag(request):
    if (request.method == "POST"):
        form = TagForm(request.POST)
        if form.is_valid():
            new_tag = Category(
                name = form.cleaned_data['tag'],
                )
            new_tag.save()
            #currently returns to the main page.
            return HttpResponseRedirect('/')
    else:
        form = TagForm()
    return render(request, 'categories/submit_tag.html', { 'form': form })

class signup(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'categories/signup.html'

SoundMixer/categories/templates/categories/list.html
{% extends "SoundMixer/base.html" %}

{% block body %}
  {% if random_song and song_id_list %}
    <b><a href="{% url 'categories:song' random_song.id song_id_list %}"> Play random song </a></b><br>
  {% endif %}
  <h3>Songs:</h3>
  {% if song_list %}
    <ul>
      {% for song in song_list %}
        <li><b><a href="{% url 'categories:song' song.id song_id_list %}">{{ song.name }}</a></b><br>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    There's nothing here :(
  {% endif %}
{% endblock %}

SoundMixer/categories/templates/categories/search.html
{% extends "SoundMixer/base.html" %}

{% block body %}
  <form action="{% url 'categories:search' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Done">
  </form>
{% endblock %}

SoundMixer/categories/templates/categories/signup.html
{% extends "SoundMixer/base.html" %}

{% block body %}
  Hey, you found me!<br>
  I'm imported from another project and I can't be assed to set it up<br>
  This might come in handy later, if someone spams the lists and we need registration<br>
  {% if user.is_authenticated %}
    You're already signed up. <a href="{% url 'logout' %}"> Click here to log out.</a>
  {% else %}
    <form action="{% url 'categories:signup' %}" method="post" >
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Sign Up">
    </form>
  {% endif %}
{% endblock %}

SoundMixer/categories/templates/categories/song.html
{% extends "SoundMixer/base.html" %}

{% block body %}
  {% if random_song and song_id_list %}
    <b><a href="{% url 'categories:song' random_song.id song_id_list %}"> Play random song from previous page</a></b><br><br>
  {% endif %}
  name: {{ song.name }}<br><br>
  <iframe width="560"
    height="315"
    src="https://www.youtube.com/embed/{{ song.link }}?autoplay=1"
    frameborder="0"
    allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
    allowfullscreen></iframe><br>
  tags:<br>
  {% for tag in song.tags.all %}
    <a href="{% url 'categories:get_tag_songs' tag.name %}">{{ tag.name }}<br></a>
  {% endfor %}
  {% if song_id_list %}
    <form action="{% url 'categories:song' song.id song_id_list %}" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Done">
    </form>
  {% else %}
    <form action="{% url 'categories:song' song.id %}" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Done">
    </form>
  {% endif %}
{% endblock %}

SoundMixer/categories/templates/categories/submit_song.html
{% extends "SoundMixer/base.html" %}

{% block body %}
  <form action="{% url 'categories:submit_song' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Done">
  </form>
{% endblock %}

SoundMixer/categories/templates/categories/submit_tag.html
{% extends "SoundMixer/base.html" %}

{% block body %}
  <form action="{% url 'categories:submit_tag' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Done">
  </form>
{% endblock %}

SoundMixer/categories/templates/categories/tags.html
{% extends "SoundMixer/base.html" %}

{% block body %}
  <h3>Tags:</h3>
  {% if tag_list %}
    <ul>
      {% for tag in tag_list %}
        <li><b><a href="{% url 'categories:get_tag_songs' tag.name %}">{{ tag.name }}</a></b>
          ({{ tag.s_count }})<br>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    There's nothing here :(
  {% endif %}
{% endblock %}

SoundMixer/templates/SoundMixer/base.html
<h1>Welcome to the DnD Playlist Machine</h1><br>

<a href="{% url 'categories:tag_list' %}"> Home</a> •
<a href="{% url 'categories:submit_song' %}"> Submit Song</a> •
<a href="{% url 'categories:submit_tag' %}"> Submit Tag</a> •
{% if user.is_superuser %}
  <a href="/admin"> Admin</a> •
{% endif %}
<a href="{% url 'categories:search' %}"> Search</a>


<br><br>

{% block body %}{% endblock %}